### ISSUE TITLE
Convert the kubernetes YAML into Terraform HCL via hashicorp kubernetes provide

### ISSUE THREAD

**Issue by tim-tschiersch** [adorsys/ops-k8s-bootstrap#43]
## Conclusion
We have to convert the kubectl_manifests from all tf's in the modules dir, because we don't want to use  the [gavinbunny](https://registry.terraform.io/providers/gavinbunney/kubectl/latest) provider anymore.

## Task
We need to convert all our manifests from kubernetes yaml into terrfarm hcl before we delete the provider. We want to use [this](https://github.com/sl1pm4t/k2tf/tree/v0.7.0) converter. Instead of the old provider we are going to use the[ hashicorp kubernetes](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) provider. 
We can also delete every [provider.tf](https://github.com/adorsys/ops-k8s-bootstrap/blob/main/bootstrap/modules/dex/provider.tf) with the gavinbunny provider inside the module section after that, because we don't need to reference the required provider anymore.

## Acceptance Criteria
- [x] gavinbunny provider only beeing used for crd's because we cannot create them in terraform hcl
- [x] the whole manifest syntax has been changed into the new one from the hashicorp [provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest)
- [x] all provider.tfs inside the modules have been deleted except those that need it for th crd's

**Comment by tim-tschiersch** [comment]
We have to take care of this

<img width="1486" alt="Bildschirmfoto 2022-11-23 um 20 38 51" src="https://user-images.githubusercontent.com/67003331/203633058-dd80e43f-615f-4e5a-bc79-dd79d87d41a8.png">
